const char * WELCOME_TEM_INDEX_HTML = 
"<script src=\"/socket.io/socket.io.js\"></script>\n"
"<script>\n"
"\tvar socket = io.connect('http://localhost');\n"
"\tsocket.on('connection', function (data) {\n"
"\n"
"\t\t////////////////////////////////////////////////////////////////\n"
"\t\t// here, the data received is a json that contains the song data\n"
"\t\tconsole.log(data);\n"
"\t\t\n"
"\t\t////////////////////////////////////////////////////////////////\n"
"\t\t//you may send data back to the server if you wish to\n"
"\n"
"\t\tsocket.emit('my other event', { my: 'data' });\n"
"\t});\n"
"\n"
"\t//////////////////////////////////////////////////////////////////\n"
"\t//this is the server reply to you if something has happened:either\n"
"\t//you or your opponent has hit something\n"
"\t//signature of the message:\n"
"\t//if you were not the sender:\n"
"\t//{\n"
"\t//\t\t'sender' : false,\n"
"\t//\t\t'opponent_hit1' : true,\n"
"\t//\t\t'opponent_hit2' : false,\n"
"\t//\t\t'opponent_hit3' : true,\n"
"\t//\t\t'score' : 2120\n"
"\t//}\n"
"\t//if you were the sender\n"
"\t//{\n"
"\t//\t\t'sender' : true,\n"
"\t//\t\t'score'\t: 2130\n"
"\t//}\n"
"\tsocket.on('serverMsg', function(message){\n"
"\n"
"\t\t/////////////////////////////////////////////////////////////////\n"
"\t\t// This is the data received from the server\n"
"\n"
"\t\tconsole.log('Message received from server');\n"
"\n"
"\t\tconsole.log(message);\n"
"\t});\n"
"\n"
"\n"
"\t//////////////////////////////////////////////////////////////////\n"
"\t// This function is used to send message to server\n"
"\t// signature:\n"
"\t// {\n"
"\t//\t\t'hit1' : true,\n"
"\t//\t\t'hit2' : false,\n"
"\t//\t\t'hit3' : true,\n"
"\t//\t\t'score' : 1234\n"
"\t// }\n"
"\tfunction sendMessage(msg)\n"
"\t{\n"
"\t\tmsg = { 'hit1' : true,\n"
"\t\t\t\t\t\t'hit2' : false,\n"
"\t\t\t\t\t\t'hit3' : true,\n"
"\t\t\t\t\t\t'score' : 1234 };\n"
"\t\t\t\tif(socket.emit('clientMsg', msg))\n"
"\t\t\t\t{\n"
"\t\t\t\t\t\tconsole.log(\"You are sending this message to the server\");\n"
"\t\t\t\t\t\tconsole.log(msg);\n"
"\t\t\t\t}\n"
"\t}\n"
"</script>\n"
"<button value=\"click me\" onclick=\"sendMessage('greeting from client')\">Click here </button>\n"
;
